friend_Name = input("Enter your friend name: ")
adjective_1 = input("Enter an adjective: ")
food_1 = input("Enter a food name: ")
noun_1= input("Enter a noun: ")
food_2 = input("Enter a food name: ")
color = input("Enter a color name: ")
clothing_item = input("Enter a clothing item: ")
noun_3 = input("Enter a noun: ")
adjective_2 = input("Enter an adjective: ")
noun_4 = input("Enter a noun: ")
liquid = input("Enter a liquid: ")
animal = input("Enter an animal: ")
verb = input("Enter a verb: ")
adjective_3 = input("Enter an adjective: ")
food_3 = input("Enter a food: ")
type_of_music = input("Enter a type of music: ")
print("*"*100)
print("WELCOME TO MAD LIBS GAME")
print("="*100)
print("The Disastrous Dinner Party")
print("="*100)
print(f"Last night, I invited my best friend, {friend_Name}, over for a {adjective_1} dinner.\nI planned to cook my famous {food_1}, but I accidentally dropped it on the {noun_1}.\nPanic set in, so I decided to order {food_2} from the local restaurant instead.\nWhen my guest arrived, they were wearing a {color} {clothing_item} and carrying a giant {noun_3}. They looked incredibly {adjective_2}! \nWe sat down to eat, but the food tasted like {noun_4} mixed with {liquid}.\nTo make matters worse, my pet {animal} started to {verb} on the table.\nMy guest shouted, 'This is the most {adjective_3} meal I have ever eaten!' We ended up eating {food_3} for dessert and dancing to {type_of_music} music until we fell over.")
print("*"*100)
print("THANK YOU FOR PLAYING MAD LIBS GAME!!!")